version: '3.8'
services:
  employees-of-itf:
    container_name: employees-of-itf
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace:cached
    env_file: .env
    ports:
      - '56216:4200' # Angular
      - '56280:8080' # Java
    command: sleep infinity
    depends_on:
        - employees-of-itf-db

  employees-of-itf-db:
    container_name: employees-of-itf-db
    image: mariadb:10.10.2-jammy
    restart: unless-stopped
    volumes:
      - employees-of-itf-db-volume:/var/lib/mariadb/
      - ../database/conf.d:/etc/mysql/conf.d
      - ../database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    env_file: .env
    ports:
      - '56290:3306'

volumes:
  employees-of-itf-db-volume:
    driver: local